// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// eigenPNTginvATNP
arma::mat eigenPNTginvATNP(arma::mat& z, arma::mat& N, arma::mat& T, arma::mat& P);
RcppExport SEXP infoDecompuTE_eigenPNTginvATNP(SEXP zSEXP, SEXP NSEXP, SEXP TSEXP, SEXP PSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< arma::mat& >::type z(zSEXP );
        Rcpp::traits::input_parameter< arma::mat& >::type N(NSEXP );
        Rcpp::traits::input_parameter< arma::mat& >::type T(TSEXP );
        Rcpp::traits::input_parameter< arma::mat& >::type P(PSEXP );
        arma::mat __result = eigenPNTginvATNP(z, N, T, P);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// eigenRcpp
Rcpp::List eigenRcpp(arma::mat& M);
RcppExport SEXP infoDecompuTE_eigenRcpp(SEXP MSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< arma::mat& >::type M(MSEXP );
        Rcpp::List __result = eigenRcpp(M);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// PNTginvATNP
arma::mat PNTginvATNP(arma::mat& z, arma::mat& N, arma::mat& T, arma::mat& P);
RcppExport SEXP infoDecompuTE_PNTginvATNP(SEXP zSEXP, SEXP NSEXP, SEXP TSEXP, SEXP PSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< arma::mat& >::type z(zSEXP );
        Rcpp::traits::input_parameter< arma::mat& >::type N(NSEXP );
        Rcpp::traits::input_parameter< arma::mat& >::type T(TSEXP );
        Rcpp::traits::input_parameter< arma::mat& >::type P(PSEXP );
        arma::mat __result = PNTginvATNP(z, N, T, P);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
