# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenPNTginvATNP <- function(z, N, T, P) {
    .Call('infoDecompuTE_eigenPNTginvATNP', PACKAGE = 'infoDecompuTE', z, N, T, P)
}

eigenRcpp <- function(M) {
    .Call('infoDecompuTE_eigenRcpp', PACKAGE = 'infoDecompuTE', M)
}

PNTginvATNP <- function(z, N, T, P) {
    .Call('infoDecompuTE_PNTginvATNP', PACKAGE = 'infoDecompuTE', z, N, T, P)
}

